name: qr_order_app_new
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  geolocator: ^10.0.0
  flutter_local_notifications: ^15.1.0+1
  
  # Firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  firebase_storage: ^11.2.6
  firebase_messaging: ^14.6.7

  # UI Components
  google_maps_flutter: ^2.4.0
  fl_chart: ^0.63.0
  qr_code_scanner: ^0.4.0
  
  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.1.14
  image_picker: ^1.0.4
  mobile_scanner: ^3.4.1
  permission_handler: ^10.4.3
  connectivity_plus: ^4.0.2
  workmanager: ^0.5.2
  csv: ^5.0.1
  share_plus: ^7.0.0
  
  # Local Storage
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3

  # State Management
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  # Add any assets or fonts here if needed
  # assets:
  #   - assets/images/